services:
  - type: web
    name: logitrackpro
    runtime: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_DIRECT
        sync: false
      - key: PORT
        value: 8080
      - key: CORS_ALLOWED_ORIGINS
        value: https://logitrackpro-henna.vercel.app
